language: node_js
node_js:
  - lts/*
install:
  - yarn install
cache:
  directories:
    - node_modules
script:
  - yarn lint
  - yarn docs:build

#after_success:
#  - npm run codecov

before_deploy: |
  function npm_dist_tag() {
    if [[ "$TRAVIS_TAG" = *"-"* ]]; then
      echo "next"
    else
      echo "latest"
    fi
  }

